In [1]:
!pip install tensorflow-gpu==1.15

     |████████████████████████████████| 411.5MB 43kB/s 
     |████████████████████████████████| 51kB 260kB/s 
     |████████████████████████████████| 512kB 34.0MB/s 
     |████████████████████████████████| 3.8MB 37.2MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7542 sha256=8e4afe3f070abbafe27a119dbdc6007012cb46a6a913448d09f53b111fbad39f
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow 2.3.0 has requirement gast==0.3.3, but you'll have gast 0.2.2 which is incompatible.
ERROR: tensorflow 2.3.0 has requirement tensorboard<3,>=2.3.0, but you'll have tensorboard 1.15.0 which is incompatible.
ERROR: tensorflow 2.3.0 has requirement tensorflow-estimator<2.4.0,>=2.3.0, but you'll have tensorflow-estimator 1.15.1 which is incompatible.
ERROR: tensorflow-probability 0.11.0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing i

In [2]:
import tensorflow_hub as hub
import tensorflow as tf

In [3]:
url = "http://files.deeppavlov.ai/deeppavlov_data/elmo_ru-news_wmt11-16_1.5M_steps.tar.gz"

In [4]:
elmo = hub.Module(url)
 
def elmo_vectors(x):
   
  embeddings=elmo(x, signature="default", as_dict=True)["elmo"]
  
  with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.tables_initializer())
    # return average of ELMo features
    return sess.run(tf.reduce_mean(embeddings,1))

In [5]:
# безопасность жизнедеятельности
corpus1 = ["показал всестороннее, систематическое и глубокое знание учебного материала, предусмотренного программой по ГОС; усвоил основную и знаком с дополнительной литературой по программе; усвоил взаимосвязь основных понятий дисциплины; умеет творчески и осознанно применять полученные знания  к анализу и решению практических задач",
           "обнаружил полное знание учебного материала, предусмотренного программой; успешно ответил на все вопросы экзаменационного билета с одним небольшим недочетом; усвоил основную литературу, рекомендованную программой дисциплины, способен к самостоятельному пополнению и обновлению знаний в ходе дальнейшей профессиональной деятельности",
           "обнаружил знание основного учебного материала, предусмотренного программой, в объеме необходимом для работы по специальности, знает основную литературу, рекомендованную программой; справился с выполнением заданий, предусмотренных программой, но допустил погрешности в ответе на экзамене; обладает необходимыми знаниями для их устранения под руководством преподавателя",
           "обнаружил пробелы в знании основного материала, предусмотренного программой, допустил принципиальные ошибки при ответе на экзаменационные вопросы, не выполнил отдельные задания, предусмотренные формами текущего контроля. Ответ студента на экзамене свидетельствует о том, что он не может продолжить обучение или приступить к профессиональной деятельности по окончании вуза без дополнительных занятий по соответствующей дисциплине"]

# системы управления хтп
corpus2 = ["ответы на поставленные вопросы излагаются логично, последовательно и не требуют дополнительных пояснений. Делаются обоснованные выводы. Демонстрируются глубокие знания учебного материала. Соблюдаются нормы литературной речи",
           "ответы на поставленные вопросы излагаются систематизировано и последовательно.  Материал излагается уверенно. Демонстрируется умение анализировать материал, однако не все выводы носят аргументированный и доказательный характер",
           "в последовательности изложения допускаются неточности.  Демонстрируются поверхностные знания вопроса, с трудом решаются конкретные задачи. Имеются затруднения с выводами",
           "материал излагается непоследовательно, сбивчиво, не представляет определенной системы знаний по дисциплине. Не проводится анализ. Выводы отсутствуют. Ответы на дополнительные вопросы отсутствуют"]

# дискретная математика
corpus3 = ["студент показывает всестороннее и глубокое знание программного материала, умение свободно выполнять задание и решать задачи по программе курса, проявляет творческие способности в понимании, изложении и применении учебного материала",
           "студент показывает полное знание программного материала, способен к самостоятельному выполнению и обновлению знаний в ходе дальнейшей учёбы и профессиональной деятельности",
           "студент показывает знание основного учебно-программного материала в объёме, необходимом для дальнейшей учёбы и профессиональной деятельности, но не в полной мере справляется с выполнением заданий, предусмотренных программой",
           "студент, показывает пробелы в знании основного учебно-программного материала, допускает принципиальные ошибки в выполнении предусмотренных программой заданий"]

In [6]:
from sklearn.metrics.pairwise import cosine_similarity

# # чем больше число, тем больше сходство
elmo_embeddings1=[]
for i in range(len(corpus1)):
    elmo_embeddings1.append(elmo_vectors([corpus1[i]])[0])

print('+++++++++++++++++++++++++++++++++++++++++++++++++++')    
print()
print('similarity matrix1 = ', cosine_similarity(elmo_embeddings1, elmo_embeddings1))

print()

elmo_embeddings2=[]
for i in range(len(corpus2)):
    elmo_embeddings2.append(elmo_vectors([corpus2[i]])[0])

print('+++++++++++++++++++++++++++++++++++++++++++++++++++')    
print()
print('similarity matrix2 = ', cosine_similarity(elmo_embeddings2, elmo_embeddings2))

print()

elmo_embeddings3=[]
for i in range(len(corpus3)):
    elmo_embeddings3.append(elmo_vectors([corpus3[i]])[0])

print('+++++++++++++++++++++++++++++++++++++++++++++++++++')    
print()
print('similarity matrix3 = ', cosine_similarity(elmo_embeddings3, elmo_embeddings3))

print()

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


+++++++++++++++++++++++++++++++++++++++++++++++++++

similarity matrix1 =  [[1.0000001  0.82799184 0.78235126 0.65834904]
 [0.82799184 0.9999999  0.85046256 0.816628  ]
 [0.78235126 0.85046256 0.99999994 0.8350488 ]
 [0.65834904 0.816628   0.8350488  1.        ]]

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


+++++++++++++++++++++++++++++++++++++++++++++++++++

similarity matrix2 =  [[1.0000002  0.8210629  0.81178784 0.8026558 ]
 [0.8210629  1.0000001  0.7162979  0.7946677 ]
 [0.81178784 0.7162979  1.0000002  0.74604344]
 [0.8026558  0.7946677  0.74604344 1.0000002 ]]

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


+++++++++++++++++++++++++++++++++++++++++++++++++++

similarity matrix3 =  [[1.0000001  0.81003475 0.71515197 0.7217858 ]
 [0.81003475 0.9999999  0.795421   0.68853474]
 [0.71515197 0.795421   0.9999998  0.7588309 ]
 [0.7217858  0.68853474 0.7588309  0.99999976]]



In [7]:
elmo1_1 = []
j = 0
for j in elmo_embeddings1[0]:
    elmo1_1.append(j)
print(elmo1_1)

print()

elmo1_2 = []
j = 0
for j in elmo_embeddings1[1]:
    elmo1_2.append(j)
print(elmo1_2)

print()

elmo1_3 = []
j = 0
for j in elmo_embeddings1[2]:
    elmo1_3.append(j)
print(elmo1_3)

print()

elmo1_4 = []
j = 0
for j in elmo_embeddings1[3]:
    elmo1_4.append(j)
print(elmo1_4)

[-0.2193327, 0.015423405, 0.019929685, 0.0968547, -0.08753023, 0.07078478, 0.52711266, -0.19565067, 0.0034967356, -0.1935976, 0.025707835, 0.27206537, 0.08662232, -0.18573032, -0.56902534, 0.12283903, 0.3791194, 0.19312504, 0.33840936, -0.7765259, 0.03934492, -0.15433033, 0.109026775, -0.2338015, 0.12557398, 0.10923448, -0.1764519, -0.30269665, 0.21198738, -0.6362215, 0.3410671, -0.019036278, 0.25063667, 0.11321188, -0.13997252, -0.29194963, -0.34746066, 0.09738757, -0.11025347, -0.13169667, 0.10392128, 0.018371986, 0.06527881, 0.33201912, -0.07641654, -0.056545008, -0.29909232, 0.048476465, 0.027090179, 0.51762503, 0.011906907, -0.10867801, -0.28624982, -0.013766926, 0.09189676, 0.37816212, 0.27768055, 0.13926516, -0.023636013, -0.038274687, 0.36884692, 0.06969382, -0.2872367, -0.23036343, 0.089603424, -0.106240064, -0.21182312, -0.33576715, 0.43328658, 0.24213962, -0.06453327, 0.49166185, -0.0144502185, -0.2957639, 0.29243034, -0.500761, -0.41547972, 0.15134786, -0.42292684, -0.43312

In [8]:
elmo2_1 = []
j = 0
for j in elmo_embeddings2[0]:
    elmo2_1.append(j)
print(elmo2_1)

print()

elmo2_2 = []
j = 0
for j in elmo_embeddings2[1]:
    elmo2_2.append(j)
print(elmo2_2)

print()

elmo2_3 = []
j = 0
for j in elmo_embeddings2[2]:
    elmo2_3.append(j)
print(elmo2_3)

print()

elmo2_4 = []
j = 0
for j in elmo_embeddings2[3]:
    elmo2_4.append(j)
print(elmo2_4)

[0.014873467, -0.13157402, -5.012378e-06, 0.2216189, -0.10538247, -0.14115255, 0.43326235, 0.11056384, 0.1374229, -0.14108576, 0.16290992, -0.18945403, 0.3183665, -0.30017465, -1.0566996, 0.040223304, 0.34360147, 0.23704357, 0.084023364, -0.30838448, 0.14713252, -0.32622105, -0.027171208, 0.06535948, -0.25810263, -0.23973514, 0.44625852, -0.45242617, 0.21228097, -0.6210113, 0.06463581, -0.1462747, 0.059146594, -0.07445532, -0.18678923, -0.08780179, -0.21395458, -0.33472934, -0.110067904, -0.6573685, 0.07394921, 0.03650332, -0.038711548, 0.056769546, 0.008918074, 0.07662082, -0.21295689, -0.08813712, 0.012985353, 0.30062643, 0.066131614, -0.5582023, -0.2272957, -0.05795595, -0.044171933, 0.7585215, 0.32362238, -0.21249305, 0.06598093, -0.20598523, -0.047316957, -0.03958111, -0.047927976, -0.048578292, 0.14544196, -0.32325342, -0.41538092, -0.16212504, 0.074320346, 0.3013852, -0.075392656, 0.00077050616, 0.15109223, -0.4588102, -0.034017, -0.3742077, -0.36694267, 0.08090732, -0.57007235,

In [9]:
elmo3_1 = []
j = 0
for j in elmo_embeddings3[0]:
    elmo3_1.append(j)
print(elmo3_1)

print()

elmo3_2 = []
j = 0
for j in elmo_embeddings3[1]:
    elmo3_2.append(j)
print(elmo3_2)

print()

elmo3_3 = []
j = 0
for j in elmo_embeddings3[2]:
    elmo3_3.append(j)
print(elmo3_3)

print()

elmo3_4 = []
j = 0
for j in elmo_embeddings3[3]:
    elmo3_4.append(j)
print(elmo3_4)

[-0.20065942, 0.18793118, -0.1465105, 0.0763824, -0.17118964, -0.05918193, 0.21824816, -0.31708297, -0.34345484, -0.0908163, -0.17339423, -0.19291046, 0.15935735, -0.18652312, -0.6226246, 0.0867662, 0.34337828, 0.19252184, 0.23527262, -0.71404964, 0.31672448, -0.1260675, -0.010917725, -0.07276658, 0.15886644, -0.043385148, -0.12037079, -0.3237052, 0.33180586, -0.81214184, 0.46589008, 0.17199656, 0.02988902, 0.11481453, -0.3914399, 0.11131785, -0.2944376, -0.0641605, -0.07840824, -0.52797925, 0.06580449, 0.13403934, 0.0579737, 0.18196942, -0.08051703, -0.05992653, 0.00396344, -0.0023131154, 0.03347404, 0.5260237, 0.09417676, -0.1258739, -0.3088307, 0.027381798, 0.3737362, 0.4671238, 0.234939, 0.2780432, 0.32813603, -0.02755467, 0.21353851, 0.09148236, -0.52226955, -0.18479678, -0.0019605309, -0.15504357, -0.19202825, -0.11635767, 0.4843812, 0.18981442, -0.37279806, 0.5048859, -0.12443528, -0.3424678, 0.3671655, -0.45990878, -0.36419424, 0.046182554, -0.4204299, -0.33670834, 0.160378, 0.

In [10]:
# # чем больше число, тем больше сходство
import numpy as np

e1_1 = np.array(elmo1_1, float)
e1_2 = np. array(elmo1_2, float)
e1_3 = np.array(elmo1_3, float)
e1_4 = np.array(elmo1_4, float)

e1_1_2 = np.dot(e1_1, e1_2)
e1_2_3 = np.dot(e1_2, e1_3)
e1_1_4 = np.dot(e1_1, e1_4)
e1_2_4 = np.dot(e1_2, e1_4)
e1_3_4 = np.dot(e1_3, e1_4)
print('5 --> 4: ', e1_1_2)
print('4 --> 3: ', e1_2_3)
print('5 --> 2: ', e1_1_4)
print('4 --> 2: ', e1_2_4)
print('3 --> 2: ', e1_3_4)

print()

e2_1 = np.array(elmo2_1, float)
e2_2 = np. array(elmo2_2, float)
e2_3 = np.array(elmo2_3, float)
e2_4 = np.array(elmo2_4, float)

e2_1_2 = np.dot(e2_1, e2_2)
e2_2_3 = np.dot(e2_2, e2_3)
e2_1_4 = np.dot(e2_1, e2_4)
e2_2_4 = np.dot(e2_2, e2_4)
e2_3_4 = np.dot(e2_3, e2_4)
print('5 --> 4: ', e2_1_2)
print('4 --> 3: ', e2_2_3)
print('5 --> 2: ', e2_1_4)
print('4 --> 2: ', e2_2_4)
print('3 --> 2: ', e2_3_4)

print()

e3_1 = np.array(elmo3_1, float)
e3_2 = np. array(elmo3_2, float)
e3_3 = np.array(elmo3_3, float)
e3_4 = np.array(elmo3_4, float)

e3_1_2 = np.dot(e3_1, e3_2)
e3_2_3 = np.dot(e3_2, e3_3)
e3_1_4 = np.dot(e3_1, e3_4)
e3_2_4 = np.dot(e3_2, e3_4)
e3_3_4 = np.dot(e3_3, e3_4)
print('5 --> 4: ', e3_1_2)
print('4 --> 3: ', e3_2_3)
print('5 --> 2: ', e3_1_4)
print('4 --> 2: ', e3_2_4)
print('3 --> 2: ', e3_3_4)

5 --> 4:  53.972541640217315
4 --> 3:  54.672527858951966
5 --> 2:  45.65105804436598
4 --> 2:  51.59774036950335
3 --> 2:  57.10493147960614

5 --> 4:  56.098246410325515
4 --> 3:  47.72751037653237
5 --> 2:  49.378707381432925
4 --> 2:  50.979595729089894
3 --> 2:  44.758652600597806

5 --> 4:  64.81192964690185
4 --> 3:  54.97834854871928
5 --> 2:  56.4411660885432
4 --> 2:  51.889124875521865
3 --> 2:  51.259686548475756


In [11]:
# чем меньше число, тем выражения более близки
from sklearn.metrics.pairwise import euclidean_distances

print('similarity matrix1 = ', euclidean_distances(elmo_embeddings1, elmo_embeddings1))
print()
print('similarity matrix2 = ', euclidean_distances(elmo_embeddings2, elmo_embeddings2))
print()
print('similarity matrix3 = ', euclidean_distances(elmo_embeddings3, elmo_embeddings3))


similarity matrix1 =  [[0.0000000e+00 4.7946653e+00 5.5429406e+00 6.8883042e+00]
 [4.7946653e+00 1.6858739e-07 4.4304304e+00 4.8387861e+00]
 [5.5429406e+00 4.4304304e+00 0.0000000e+00 4.7519326e+00]
 [6.8883042e+00 4.8387861e+00 4.7519326e+00 0.0000000e+00]]

similarity matrix2 =  [[0.0000000e+00 4.9569516e+00 4.9083900e+00 4.9522920e+00]
 [4.9569516e+00 0.0000000e+00 6.1729932e+00 5.2011280e+00]
 [4.9083900e+00 6.1729932e+00 0.0000000e+00 5.5279574e+00]
 [4.9522920e+00 5.2011280e+00 5.5279574e+00 1.6858739e-07]]

similarity matrix3 =  [[0.0000000e+00 5.5233908e+00 6.5112610e+00 6.6174884e+00]
 [5.5233908e+00 0.0000000e+00 5.3952508e+00 6.8545437e+00]
 [6.5112610e+00 5.3952508e+00 2.0647654e-07 5.7522025e+00]
 [6.6174884e+00 6.8545437e+00 5.7522025e+00 0.0000000e+00]]


In [12]:
# чем меньше число, тем выражения более близки
from sklearn.metrics.pairwise import manhattan_distances

print('similarity matrix1 = ', manhattan_distances(elmo_embeddings1, elmo_embeddings1))
print()
print('similarity matrix2 = ', manhattan_distances(elmo_embeddings2, elmo_embeddings2))
print()
print('similarity matrix3 = ', manhattan_distances(elmo_embeddings3, elmo_embeddings3))

similarity matrix1 =  [[  0.         121.71879446 141.78951659 172.28886012]
 [121.71879446   0.         113.27030859 123.54338438]
 [141.78951659 113.27030859   0.         119.97674357]
 [172.28886012 123.54338438 119.97674357   0.        ]]

similarity matrix2 =  [[  0.         126.20102298 124.45982016 127.78773321]
 [126.20102298   0.         153.74986323 131.86899872]
 [124.45982016 153.74986323   0.         140.29559689]
 [127.78773321 131.86899872 140.29559689   0.        ]]

similarity matrix3 =  [[  0.         139.74129328 159.88387375 165.60549674]
 [139.74129328   0.         135.85650162 171.56051927]
 [159.88387375 135.85650162   0.         143.00717858]
 [165.60549674 171.56051927 143.00717858   0.        ]]


In [13]:
def minkowski(a, b, p=4):
    assert len(a) == len(b), "'a' and 'b' must be of the same length"
    return pow(sum((abs(x-y)**p) for x,y in zip(a,b)), 1/p)

print(minkowski(e1_1, e1_2))
print(minkowski(e1_2, e1_3))
print('5-->2', minkowski(e1_1, e1_4))
print('4-->2', minkowski(e1_2, e1_4))
print('3-->2', minkowski(e1_3, e1_4))
print()
print(minkowski(e2_1, e2_2))
print(minkowski(e2_2, e2_3))
print('5-->2', minkowski(e2_1, e2_4))
print('4-->2', minkowski(e2_2, e2_4))
print('3-->2', minkowski(e2_3, e2_4))
print()
print(minkowski(e3_1, e3_2))
print(minkowski(e3_2, e3_3))
print('5-->2', minkowski(e3_1, e3_4))
print('4-->2', minkowski(e3_2, e3_4))
print('3-->2', minkowski(e3_3, e3_4))

1.127996649457108
1.0409586236345965
5-->2 1.6447313969358788
4-->2 1.1329388222256342
3-->2 1.1132894518840473

1.144631459193604
1.464310872175831
5-->2 1.1347672528801898
4-->2 1.2116245745483245
3-->2 1.2819151914508145

1.299164680114443
1.302316086982698
5-->2 1.5708911909734007
4-->2 1.6739773645744387
3-->2 1.4056109395710386


In [15]:
print(e1_1)

[-0.2193327   0.0154234   0.01992968 ...  0.57813597 -0.15771779
  0.6048367 ]
